# cmake -G Ninja -S llvm-project/llvm -B build -C cmake/caches/LLVM-MinSizeRel.cmake
include(${CMAKE_CURRENT_LIST_DIR}/LLVM.cmake)

set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING "")

set(LLVM_DISTRIBUTION_COMPONENTS
  ${HYLO_LLVM_DISTRIBUTION_LIBRARIES}
  ${HYLO_LLVM_DISTRIBUTION_SUPPORT}
  ${HYLO_LLVM_DISTRIBUTION_TOOLS}
  CACHE STRING "")
