name: build-llvm-binaries

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'LLVM Version'
        default: '17.0.6'
        required: false
        type: string

env:
  SCCACHE_DIRECT: yes

jobs:
  build_tools:
    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x86_64, arm64]

        include:
          # Default values
          - c_compiler: clang
          - cxx_compiler: clang++
          - toolset_suffix:
          - lldb_enable_libxml2_option:
          - llvm_enable_zstd_option:
          - into_environment: '>> $GITHUB_ENV'
          - executable_suffix:
          - llvm_enable_projects: 'clang;lld'
          - static_lib_suffix: .a
          - package_command: tar cjf
          - package_suffix: .tar.bz2
          - compile_cache: sccache
          - llvm_target_arch_option:
          - cmake_system_processor_option:
          - cmake_find_root_path_option:
          - triple_cpu:

          # Overrides
          - os: windows-latest

            into_environment: '| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append'
            c_compiler: cl
            cxx_compiler: cl
            toolset_suffix: -msvc17
            executable_suffix: .exe
            llvm_enable_projects: 'clang;lld;lldb'
            static_lib_suffix: .lib
            package_command: 7z a -t7z
            package_suffix: .7z

          - os: macos-latest

            # compile_cache: ccache
            llvm_enable_zstd_option: -D LLVM_ENABLE_ZSTD=NO

          - arch: x86_64

            triple_cpu: x86_64

          - arch: arm64

            lldb_enable_libxml2_option: -D LLDB_ENABLE_LIBXML2=NO
            llvm_target_arch_option: -D LLVM_TARGET_ARCH=arm64
            cmake_system_processor_option: -D CMAKE_SYSTEM_PROCESSOR=arm64
            cmake_find_root_path_option: >-
              -D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
              -D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
              -D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
              -D CMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY

            triple_cpu: arm64

          - arch: arm64
            os: ubuntu-latest

            triple_cpu: aarch64
            c_compiler: gcc
            cxx_compiler: g++

          # Extensions
          - os: windows-latest

            cmake_system_name: Windows
            triple_suffix: unknown-windows-msvc17

          - os: ubuntu-latest

            cmake_system_name: Linux
            triple_suffix: unknown-linux-gnu

          - os: macos-latest

            cmake_system_name: Darwin
            triple_suffix: apple-darwin23.3.0

    runs-on: ${{ matrix.os }}

    env:
      # Must be a full version string from https://www.nuget.org/packages/pythonarm64
      PYTHON_VERSION: 3.12.2
      TARGET_TRIPLE: ${{ matrix.triple_cpu }}-${{ matrix.triple_suffix }}
      PACKAGE_NAME: llvm-${{ inputs.llvm_version }}-${{ matrix.triple_cpu }}-${{ matrix.triple_suffix }}-release
      llvm_host_triple_option: ${{ matrix.arch != 'x86_64' && format('-D LLVM_HOST_TRIPLE={0}-{1}', matrix.triple_cpu, matrix.triple_suffix) || '' }}
      cmake_c_compiler_target_option: ${{ matrix.arch != 'x86_64' && format('-D CMAKE_C_COMPILER_TARGET={0}-{1}', matrix.triple_cpu, matrix.triple_suffix) || '' }}
      cmake_cxx_compiler_target_option: ${{ matrix.arch != 'x86_64' && format('-D CMAKE_CXX_COMPILER_TARGET={0}-{1}', matrix.triple_cpu, matrix.triple_suffix) || '' }}
      cmake_system_name_option: ${{ matrix.arch != 'x86_64' && format('-D CMAKE_SYSTEM_NAME={0}', matrix.cmake_system_name) || '' }}
      maybe_cross_tools_option: >-
        -D CLANG_TABLEGEN=${{ github.workspace }}/BinaryCache/0/bin/clang-tblgen${{ matrix.executable_suffix }}
        -D CLANG_TIDY_CONFUSABLE_CHARS_GEN=${{ github.workspace }}/BinaryCache/0/bin/clang-tidy-confusable-chars-gen${{ matrix.executable_suffix }}
        -D LLDB_TABLEGEN=${{ github.workspace }}/BinaryCache/0/bin/lldb-tblgen${{ matrix.executable_suffix }}
        -D LLVM_CONFIG_PATH=${{ github.workspace }}/BinaryCache/0/bin/llvm-config${{ matrix.executable_suffix }}
        -D LLVM_NATIVE_TOOL_DIR=${{ github.workspace }}/BinaryCache/0/bin
        -D LLVM_TABLEGEN=${{ github.workspace }}/BinaryCache/0/bin/llvm-tblgen${{ matrix.executable_suffix }}


    steps:
      - uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: llvmorg-${{ inputs.llvm_version }}
          path: ${{ github.workspace }}/SourceCache/llvm-project
          show-progress: false

      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/SourceCache/llvm-build
          show-progress: false

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      - name: Setup ${{ matrix.compile_cache }}
        uses: compnerd/ccache-action@sccache-0.7.4
        with:
          max-size: 1000M
          key: ${{ matrix.compile_cache }}-${{ matrix.os }}-${{ matrix.arch }}
          variant: ${{ matrix.compile_cache }}

      - name: Install Python ${{ env.PYTHON_VERSION }} (Host)
        uses: actions/setup-python@v5
        id: python
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Export Host Python Location
        run: echo "TARGET_PYTHON_LOCATION=${{ env.pythonLocation }}" ${{ matrix.into_environment }}

      # TODO(lxbndr) use actions/cache to improve this step timings
      - name: Install Python ${{ env.PYTHON_VERSION }} (arm64)
        if: ${{ matrix.arch == 'arm64' && matrix.os == 'windows-latest' }}
        run: |
          nuget install pythonarm64 -Version ${{ env.PYTHON_VERSION }}
          echo "TARGET_PYTHON_LOCATION=${{ github.workspace }}/pythonarm64.${{ env.PYTHON_VERSION }}/tools" ${{ matrix.into_environment }}

      # setup-vsdevenv doesn't properly overwrite an earlier setup.
      - name: save Windows environment
        if: ${{ matrix.os == 'windows-latest' }}
        run: Get-ChildItem env: | Export-CliXml ./pre-vsdevenv-environment.clixml

      - uses: compnerd/gha-setup-vsdevenv@main

      - name: Configure Tools
        if: ${{ matrix.arch != 'x86_64' }}
        run: >-

          cmake -B ${{ github.workspace }}/BinaryCache/0
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -D CMAKE_C_COMPILER_LAUNCHER=${{ matrix.compile_cache }}
          -D CMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
          -D CMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.compile_cache }}
          -D CMAKE_MT=mt
          -G Ninja
          -S ${{ github.workspace }}/SourceCache/llvm-project/llvm
          -D LLVM_ENABLE_ASSERTIONS=NO
          -D LLVM_ENABLE_LIBEDIT=NO
          -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lldb"
          -D LLDB_ENABLE_PYTHON=NO
          -D LLDB_INCLUDE_TESTS=NO

      - name: Build tools
        if: ${{ matrix.arch != 'x86_64' }}
        run: >-

          cmake --build ${{ github.workspace }}/BinaryCache/0
          --target llvm-tblgen
          --target clang-tblgen
          --target lldb-tblgen
          --target llvm-config
          --target clang-pseudo-gen
          --target clang-tidy-confusable-chars-gen

      # setup-vsdevenv doesn't properly overwrite an earlier setup.
      - name: Restore Windows environment
        if: ${{ matrix.os == 'windows-latest' }}
        run: Import-CliXml ./pre-vsdevenv-environment.clixml | % { Set-Item "env:$($_.Name)" $_.Value }

      - uses: compnerd/gha-setup-vsdevenv@main
        if: matrix.os == 'windows-latest'
        with:
          host_arch: amd64
          toolset_version: 14.37.32822
          components: 'Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64;Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64'
          arch: ${{ matrix.arch }}

      - name: Workaround MSVC#10444970
        if: ${{ matrix.arch == 'arm64' && matrix.os == 'windows-latest' }}
        run: |
          $clangTooling = "${{ github.workspace }}/SourceCache/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/CMakeLists.txt"
          Set-Content $clangTooling @"
          $(Get-Content -Raw $clangTooling)
          set_source_files_properties(StandardLibrary.cpp PROPERTIES
            COMPILE_FLAGS "/Od /Gw /Oi /Oy /Gw /Ob2 /Ot /GF")
          "@

          $clangCodeGen = "${{ github.workspace }}/SourceCache/llvm-project/clang/lib/CodeGen/CMakeLists.txt"
          Set-Content $clangCodeGen @"
          $(Get-Content -Raw $clangCodeGen)
          set_source_files_properties(CGBuiltin.cpp PROPERTIES
            COMPILE_FLAGS "/Od /Gw /Oi /Oy /Gw /Ob2 /Ot /GF")
          "@

      - name: Configure LLVM
        run: >-

          cmake -GNinja
          -S ${{ github.workspace }}/SourceCache/llvm-project/llvm
          -B ${{ github.workspace }}/BinaryCache/1
          -C ${{ github.workspace }}/SourceCache/llvm-build/cmake/caches/LLVM.cmake
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -D CMAKE_C_COMPILER_LAUNCHER=${{ matrix.compile_cache }}
          ${{ env.cmake_c_compiler_target_option }}
          -D CMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
          -D CMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.compile_cache }}
          ${{ env.cmake_cxx_compiler_target_option }}
          ${{ matrix.cmake_find_root_path_option }}
          -D CMAKE_MT=mt
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/BuildRoot/${{ env.PACKAGE_NAME }}
          ${{ env.cmake_system_name_option }}
          ${{ matrix.cmake_system_processor_option }}
          ${{ matrix.arch != 'x86_64' && env.maybe_cross_tools_option || '' }}
          -D LLVM_USE_HOST_TOOLS=NO
          -D CLANG_VENDOR=hylo-lang.org
          -D CLANG_VENDOR_UTI=org.hylo-lang.dt
          -D PACKAGE_VENDOR=hylo-lang.org
          -D LLVM_APPEND_VC_REV=NO
          -D LLVM_ENABLE_PROJECTS="${{ matrix.llvm_enable_projects }}"
          ${{ matrix.llvm_enable_zstd_option }}
          ${{ env.llvm_host_triple_option }}
          -D LLVM_PARALLEL_LINK_JOBS=2
          ${{ matrix.llvm_target_arch_option }}
          -D LLVM_VERSION_SUFFIX=""
          ${{ matrix.lldb_enable_libxml2_option }}
          -D LLDB_PYTHON_EXE_RELATIVE_PATH=python${{ matrix.executable_suffix }}
          -D LLDB_PYTHON_EXT_SUFFIX=.pyd
          -D LLDB_PYTHON_RELATIVE_PATH=lib/site-packages
          -D Python3_EXECUTABLE=${{ steps.python.outputs.python-path }}
          -D Python3_INCLUDE_DIR=${{ env.TARGET_PYTHON_LOCATION }}/include
          -D Python3_LIBRARY=${{ env.TARGET_PYTHON_LOCATION }}/libs/python312${{ matrix.static_lib_suffix }}
          -D Python3_ROOT_DIR=${{ env.pythonLocation }}

      - name: Build LLVM
        run: cmake --build ${{ github.workspace }}/BinaryCache/1

      - name: Install LLVM
        run: cmake --build ${{ github.workspace }}/BinaryCache/1 --target install

      - name: Package LLVM
        working-directory: ${{ github.workspace }}/BuildRoot/
        run: >-

          ${{ matrix.package_command }}
          ${{ github.workspace }}/${{ env.PACKAGE_NAME }}.${{ matrix.package_suffix }}
          ${{ env.PACKAGE_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PACKAGE_NAME }}.${{ matrix.package_suffix }}
